services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    container_name: kc
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - ./import:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
